### ISSUE TITLE
Bandwidth of RBF

### ISSUE THREAD

**Issue by BrandonHanx** [subin-kim-cv/CSD#2]
Hi @subin-kim-cv 

Thanks for your interesting work!

May I ask what's the bandwidth ``h`` of RBF in the proposed CSD-Edit when using L2 as the distance?
Does it follow the same strategy in text-to-3D generation?

**Comment by subin-kim-cv** [comment]
For the kernel bandwidth, we follow the popular median tricks. 

In detail, we use **h = med^2 / log B** , where med is the
median of the pairwise distance between the samples, and B is the mini-batch size.
As a distance metric, we used L2 for text-guided editing tasks and LPIPS for text-to-3D generation. 

You can find more details in the Appendix of our paper.
