### ISSUE TITLE
Issue of 3D editing

### ISSUE THREAD

**Issue by ShianDu** [subin-kim-cv/CSD#5]
Hi, thanks for great work!

For 3D editing pipeline, I raise an issue when reading the paper. I wonder if I understand it correctly.
1. render multi-view images by pre-trained NeRF.
2. encode all images into latents by VAE.
3. update all latents by Eqn. (9) but do not update NeRF parameters.
4. decode edited latents to images.
5. use edited images to finetune NeRF parameters.

I wonder whether the pipeline above is correct. Thx :)

**Comment by subin-kim-cv** [comment]
We do not update all latents at once. We perform editing on a subset of training views and update them sequentially at training iterations with intervals following Instruct-NeRF2NeRF.

**Comment by ShianDu** [comment]
Get it. Thx!

Besides, could you provide the code for 3D editing? Thx :)
