### ISSUE TITLE
Release code for 3D nerf editing

### ISSUE THREAD

**Issue by lai888123321** [subin-kim-cv/CSD#6]
Thank you for your great work!!!

I currently have issue of adapting CS-edit into instruct nerf2nerf. Could you please release the code for 3D nerf editing? Thank you

**Comment by subin-kim-cv** [comment]
We do not plan to release the code for CSD-Edit combined with instruct nerf2nerf experiments. 
I belive you can easily apply CSD to instruct nerf2nerf experiment using the official instruct nerf2nerf code repository. 

By the way, if you need the code, please email me.
